leads/urls.py
from django.urls import path

from . import views

app_name = 'leads'

urlpatterns = [
    path('', views.LeadListView.as_view(), name='lead_list'),
    path('create/', views.LeadCreateView.as_view(), name='lead_create'),
    path('<int:pk>/', views.LeadDetailView.as_view(), name='lead_detail'),
    path('<int:pk>/update/', views.LeadUpdateView.as_view(), name='lead_update'),
    path('<int:pk>/delete/', views.LeadDeleteView.as_view(), name='lead_delete'),
]

organizations/urls.py
from django.urls import path, include

from . import views

app_name = 'organizations'


urlpatterns = [
    path('', views.OrganizationListView.as_view(), name='organization_list'),
    path('create/', views.OrganizationCreateView.as_view(), name='organization_create'),
    path('<int:org_id>/profile/', views.OrganizationDetailView.as_view(),
         name='organization_detail'),
    path('<int:org_id>/invite/', views.OrganizationInviteView.as_view(),
         name='organization_invite'),
    path('join/<str:token>/', views.OrganizationJoinView.as_view(), name='organization_join'),
    path('<int:org_id>/leads/', include(('leads.urls', 'leads'), namespace='leads')),
    path('<int:org_id>/analytics/', include(('analytics.urls', 'analytics'),
                                            namespace='analytics')),
    path('<int:org_id>/leads-api/', include(('leads_api.urls', 'leads_api'),
                                            namespace='leads_api')),
]

pycrm/urls.py
from django.contrib import admin
from django.urls import path, include
from organizations.views import MainPage


urlpatterns = [
    path('adm/', admin.site.urls),
    path('', MainPage, name='main_page'),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('organizations/', include(('organizations.urls', 'organizations'),
                                   namespace='organizations')),
    path('users-api/', include(('users_api.urls', 'users_api'), namespace='users_api')),
]

organizations/models.py
from django.db import models
from django.contrib.auth import get_user_model

import uuid


User = get_user_model()


class Organization(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self) -> str:
        return self.name


class Membership(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)
    role = models.CharField(max_length=30, default='manager')


class MembershipInvitation(models.Model):
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)
    email = models.EmailField()
    token = models.UUIDField(default=uuid.uuid4, editable=False)

organizations/forms.py
from django import forms
from .models import Organization, MembershipInvitation


class OrganizationCreateForm(forms.ModelForm):
    class Meta:
        model = Organization
        fields = ['name', ]
        labels = {
            'name': 'Название',
        }


class InvitationForm(forms.ModelForm):
    class Meta:
        model = MembershipInvitation
        fields = ['email', ]

organizations/views.py
from typing import Any, Dict

from django.db.models import QuerySet, Model
from django.forms import Form
from django.http import HttpResponseForbidden, HttpResponseRedirect
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404, render, redirect
from django.core.mail import send_mail
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views import generic
from django.contrib.auth import get_user_model

from .forms import OrganizationCreateForm, InvitationForm
from .models import Organization, Membership, MembershipInvitation
from leads.views import VerifyMembershipMixin

User = get_user_model()


class VerifyOwnershipMixin(PermissionRequiredMixin):
    """Verifies that user has the necessary membership to access a resource."""

    def has_permission(self) -> bool:
        """
        Checks if user has the necessary membership.

        Returns:
            bool: True if user has necessary membership, False otherwise.
        """
        user = self.request.user
        organization = get_object_or_404(Organization, id=self.kwargs['org_id'])
        membership = Membership.objects.filter(user=user, organization=organization).first()

        if membership.role == 'owner':
            return True

        return False

    def handle_no_permission(self) -> HttpResponseForbidden:
        """
        Handles the case when the user doesn't have the permission.

        Returns:
            HttpResponseForbidden: 403 response when access is denied.
        """
        return HttpResponseForbidden()


def MainPage(request):
    """A view to display a main page"""

    return render(request, 'main_page.html')


class OrganizationListView(LoginRequiredMixin, generic.ListView):
    """A view for displaying a list of organizations"""

    template_name = 'organizations/organization_list.html'
    context_object_name = 'organizations'

    def get_queryset(self) -> QuerySet[Any]:
        """Returns a queryset of organizations which user has a membership in."""
        user = self.request.user
        memberships = Membership.objects.filter(user=user)
        organizations = Organization.objects.filter(pk__in=memberships.values('organization'))
        return organizations


class OrganizationCreateView(LoginRequiredMixin, generic.CreateView):
    """A view for creating a new organization"""

    model = Organization
    form_class = OrganizationCreateForm
    template_name = 'organizations/organization_create.html'
    success_url = reverse_lazy('organizations:organization_list')

    def form_valid(self, form: Form) -> HttpResponseRedirect:
        """
        Creates a membership model instance after a valid form is submitted.

        Args:
            form: The validated form.

        Returns:
            HttpResponseRedirect: The HTTP response after processing the form.
        """

        user = self.request.user
        organization = form.save(commit=False)
        organization.save()
        Membership.objects.create(user=user, organization=organization, role='owner')
        return super().form_valid(form)


class OrganizationDetailView(VerifyMembershipMixin, generic.DetailView):
    """A view for displaying details of an organization."""

    template_name = 'organizations/organization_detail.html'
    context_object_name = 'organization'
    queryset = Organization.objects.all()

    def get_object(self, queryset: QuerySet[Any] | None = ...) -> Model:
        """Returns the object the view is displaying."""

        org_id = self.kwargs['org_id']
        return get_object_or_404(self.get_queryset(), id=org_id)

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        """Provides data for the context dictionary."""

        context = super().get_context_data(**kwargs)
        org_id = self.kwargs['org_id']
        user = self.request.user
        memberships = Membership.objects.filter(organization=org_id)
        user_is_owner = get_object_or_404(memberships, user=user).role == 'owner'
        user_ids = memberships.values_list('user', flat=True)
        members = User.objects.filter(id__in=user_ids)
        context['members'] = members
        context['user_is_owner'] = user_is_owner
        return context


class OrganizationInviteView(VerifyOwnershipMixin, generic.FormView):
    """A view for inviting users to the organization."""

    form_class = InvitationForm
    template_name = 'organizations/organization_invite.html'
    success_url = reverse_lazy('organizations:organization_list')

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        """Provides data for the context dictionary."""

        context = context = super().get_context_data(**kwargs)
        org_id = self.kwargs['org_id']
        organization = Organization.objects.get(id=org_id)
        context['org_id'] = org_id
        context['organization'] = organization
        return context

    def form_valid(self, form):
        """
        Creates and sends the invitation to user if submitted form is valid
        and all conditions are met.
        """
        email = form.cleaned_data['email']
        organization = get_object_or_404(Organization, id=self.kwargs['org_id'])

        try:
            user = User.objects.get(email__iexact=email)
        except User.DoesNotExist:
            form.add_error('email', 'Пользователя с таким email не существует')
            return self.form_invalid(form)

        try:
            membership = Membership.objects.get(user=user, organization=organization)
            form.add_error('email', 'Этот пользователь уже состоит в вашей организации')
            return self.form_invalid(form)
        except Membership.DoesNotExist:
            # Deleting old invitation if exists
            old_invitation = MembershipInvitation.objects.filter(
                organization=organization,
                email=email
                ).first()
            if old_invitation:
                old_invitation.delete()

            # Creating and sending new invitation
            invitation = MembershipInvitation.objects.create(organization=organization, email=email)
            link = self.request.build_absolute_uri(reverse_lazy(
                "organizations:organization_join",
                kwargs={"token": invitation.token}
                ))
            send_mail(
                f'Organization {organization} invites you to join it',
                f'To accept the invitation click the link below:\n\n{link}',
                'noreply@example.com',
                [email],
                fail_silently=False,
                )
            return super().form_valid(form)


class OrganizationJoinView(LoginRequiredMixin, generic.TemplateView):
    """A view for joining the organization."""

    template_name = 'organizations/organization_join.html'
    success_url = reverse_lazy('organizations:organization_list')

    def get(self, request, *args, **kwargs):
        token = self.kwargs['token']
        try:
            invitation = MembershipInvitation.objects.get(token=token)
        except MembershipInvitation.DoesNotExist:
            return redirect(reverse_lazy('organizations:organization_list'))
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        token = self.kwargs['token']
        invitation = get_object_or_404(MembershipInvitation, token=token)
        Membership.objects.create(
            user=request.user,
            organization=invitation.organization,
        )
        invitation.delete()
        return redirect(reverse_lazy('organizations:organization_list'))

organizations/templates/organizations/organization_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load bootstrap4 %}

{% block title %} Создание новой организации {% endblock %}

{% block content %}
    <section class="content-header">
        <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
            <h1>Создать организацию</h1>
            </div>
            <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item active"><a href="{% url 'main_page' %}">Главная</a></li>
                <li class="breadcrumb-item">Создание организацию</li>
            </ol>
            </div>
        </div>
    </section>
    
    <section class="content">
        <div class="container">
            <div class="d-flex justify-content-center">
                <div class="col-lg-6">
                    <form method="post" class="text-center">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button type="submit" class="btn btn-primary btn-lg w-50">Создать</button>
                    </form>
                </div>
            </div>
        </div>
    </section>

    <hr />
    <a href="{% url 'organizations:organization_list' %}">Go back to your organizations</a>
{% endblock %}

organizations/templates/organizations/organization_detail.html
{% extends 'base.html' %}

{% block title %}
   Профайл организации {{ organization }}
{% endblock %}

{% block content %}
    <section class="content-header">
        <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Список пользователей, состоящих в {{ organization }}:</h1>
            </div>
            <div class="col-sm-6 d-none d-sm-block">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item active"><a href="{% url 'main_page' %}">Главная</a></li>
                    <li class="breadcrumb-item active">{{ organization.name }}</li>
                </ol>
            </div>
        </div>
        </div>
    </section>

    <section class="content-body">
        {% for member in members %}
            <div>
                <ul>
                    <li>{{ member }}</li>
                </ul>
            </div>    
        {% endfor %}

        <br />
        <hr />
        <br />

        {% if user_is_owner %}
            <a class="btn btn-primary btn-lg" href="{% url 'organizations:organization_invite' organization.pk %}">
                <i class="fas fa-user-plus"></i>
                Пригласить пользователей
            </a>
        {% endif %}
    </section>
{% endblock %}

organizations/templates/organizations/organization_invite.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load bootstrap4 %}

{% block title %} Приглашение пользователей в организацию{% endblock %}

{% block content %}
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Пригласить пользователя в организацию {{ organization.name }}</h1>
                </div>
                <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item active"><a href="{% url 'main_page' %}">Главная</a></li>
                    <li class="breadcrumb-item"><a href="{% url 'organizations:organization_detail' org_id %}">{{ organization.name }}</a></li>
                    <li class="breadcrumb-item">Приглашение пользователей</li>
                </ol>
                </div>
        </div>
    </section>
    
    <section class="content">
        <div class="container">
            <div class="d-flex justify-content-center">
                <div class="col-lg-6">
                    <form method="post" class="text-center">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button type="submit" class="btn btn-primary btn-lg w-50">Пригласить</button>
                    </form>
                </div>
            </div>
        </div>
    </section>

    <hr />
    <a href="{% url 'organizations:organization_detail' org_id %}">Go back to your organization</a>
{% endblock %}

organizations/templates/organizations/organization_join.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load bootstrap4 %}

{% block title %} Присоединение к организации {% endblock %}

{% block content %}
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Подтвердите принятие приглашения</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item active"><a href="{% url 'main_page' %}">Главная</a></li>
                        <li class="breadcrumb-item"><a href="{% url 'organizations:organization_list' %}">Организации</a></li>
                        <li class="breadcrumb-item">Присоединение к организации</li>
                    </ol>
                </div>
            </div>
        </div>
    </section>
    
    <section class="content">
        <div class="d-flex justify-content-left">
            <div class="col-lg-6">
                <form method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary btn-lg">Присоединиться</button>
                </form>
            </div>
        </div>
    </section>
{% endblock %}

organizations/templates/organizations/organization_list.html
{% extends 'base.html' %}

{% block title %} Список организаций {% endblock %}

{% block content %}
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Вы состоите в организациях:</h1>
            </div>
            <div class="col-sm-6 d-none d-sm-block">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item active"><a href="{% url 'main_page' %}">Главная</a></li>
                    <li class="breadcrumb-item active">Список организаций</li>
                </ol>
            </div>
        </div>
      </div>
    </section>

    <section class="content">
        {% if organizations %}  
            {% for organization in organizations %}
                <div>
                    <ol>
                        <h2>
                            <li>
                                <a href="{% url 'organizations:organization_detail' organization.pk %}">
                                    {{ organization.name }}
                                </a>
                                —
                                <a class="btn btn-primary btn-md" href="{% url 'organizations:analytics:general_report' org_id=organization.pk %}">
                                    <i class="fas fa-table"></i>
                                    Посмотреть заявки
                                </a>
                            </li>
                        </h2> 
                    </ol>
                </div>
            {% endfor %}
         {% else %}
            <p>Вы не состоите в организациях, создайте новую или попросите владельца существующей
                организации выслать приглашение на вашу почту.
            </p>
        {% endif %}
    <br />
    <hr />
    <br />
        <div>
            <a class="btn btn-primary btn-lg" href="{% url 'organizations:organization_create' %}">
                Создать организацию
            </a>
        </div>
    </section>

    <br />

{% endblock %}