leads/urls.py
from django.urls import path

from . import views

app_name = 'leads'

urlpatterns = [
    path('', views.LeadListView.as_view(), name='lead_list'),
    path('create/', views.LeadCreateView.as_view(), name='lead_create'),
    path('<int:pk>/', views.LeadDetailView.as_view(), name='lead_detail'),
    path('<int:pk>/update/', views.LeadUpdateView.as_view(), name='lead_update'),
    path('<int:pk>/delete/', views.LeadDeleteView.as_view(), name='lead_delete'),
]

pycrm/urls.py
from django.contrib import admin
from django.urls import path, include
from organizations.views import MainPage


urlpatterns = [
    path('adm/', admin.site.urls),
    path('', MainPage, name='main_page'),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('organizations/', include(('organizations.urls', 'organizations'),
                                   namespace='organizations')),
    path('users-api/', include(('users_api.urls', 'users_api'), namespace='users_api')),
]

users/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views

from . import views

app_name = 'users'

urlpatterns = [
     path('signup/', views.UserSignupView.as_view(), name='signup'),
     path('login/', auth_views.LoginView.
          as_view(template_name='users/login.html'), name='login'),
     path('logout/', auth_views.LogoutView.as_view(), name='logout'),
     path('password-reset/', auth_views.PasswordResetView.as_view(
            template_name='users/password_reset.html',
            email_template_name='users/password_reset_email.html',
            success_url=reverse_lazy('users:password_reset_done')
            ), name='password_reset'),
     path('password-reset/done/', auth_views.PasswordResetDoneView.
          as_view(template_name='users/password_reset_done.html'),
          name='password_reset_done'),
     path('password-reset/confirm/<uidb64>/<token>/',
          auth_views.PasswordResetConfirmView.
          as_view(template_name='users/password_reset_confirm.html',
                  success_url=reverse_lazy('users:password_reset_complete')),
          name='password_reset_confirm'),
     path('password-reset/complete/', auth_views.PasswordResetCompleteView.
          as_view(template_name='users/password_reset_complete.html'),
          name='password_reset_complete'),
     path('password-change/', auth_views.PasswordChangeView.as_view(
         template_name='users/password_change.html',
         success_url=reverse_lazy('users:password_change_done')
     ), name='password_change'),
     path('password-change/done/', auth_views.PasswordChangeDoneView.
          as_view(template_name='users/password_reset_complete.html'), name='password_change_done'),
     path('<int:pk>/profile/', views.UserProfileView.as_view(), name='user_profile'),
     path('<int:pk>/update/', views.UserUpdateView.as_view(), name='user_update'),
     path('<int:pk>/delete/', views.UserDeleteView.as_view(), name='user_delete'),
]

users/models.py
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

users/forms.py
from typing import Any

from django.contrib.auth.forms import UserCreationForm, UsernameField, UserChangeForm
from django.contrib.auth import get_user_model
from django.forms import PasswordInput

User = get_user_model()


class SignupForm(UserCreationForm):

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        pwd1 = self.fields['password1']
        pwd2 = self.fields['password2']
        pwd1.label = 'Пароль'
        pwd1.help_text = 'Пароль не должен быть слишком схож с другой персональной информацией.\
            <br /> Длинна пароля должна быть не менее 8 символов.\
                <br /> Пароль не должен быть слишком простым. \
                    <br /> Пароль не может состоять только из цифр.'
        pwd2.label = 'Подтвердите пароль'
        pwd2.help_text = 'Введите пароль повторно для проверки.'

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name')
        field_classes = {'username': UsernameField}
        labels = {
            'username': 'Имя пользователя',
            'email': 'Емейл',
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }


class UserUpdateForm(UserChangeForm):
    password = None

    class Meta:
        model = User
        fields = ['email', 'first_name', 'last_name', ]

users/views.py
from typing import Any, Dict

from django.forms.models import BaseModelForm
from django.http import HttpResponse, HttpResponseForbidden
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.shortcuts import get_object_or_404

from .forms import SignupForm, UserUpdateForm

User = get_user_model()


class VerifyUserMixin(PermissionRequiredMixin):
    """Verifies that user has the necessary membership to access a resource."""

    def has_permission(self) -> bool:
        """
        Checks if requesting user is operating with their own profile.

        Returns:
            bool: True if user has necessary membership, False otherwise.
        """
        user = get_object_or_404(User, id=self.kwargs['pk'])
        requesting_user = self.request.user
        return user == requesting_user

    def handle_no_permission(self) -> HttpResponseForbidden:
        """
        Handles the case when the user doesn't have the permission.

        Returns:
            HttpResponseForbidden: 403 response when access is denied.
        """
        return HttpResponseForbidden()


class GetQuerysetAndContextObjectNameMixin:
    """Provides queryset and context object name for User model."""

    context_object_name = 'user'
    queryset = User.objects.all()


class UserSignupView(generic.CreateView):
    """A view for creating a new user."""

    template_name = 'users/signup.html'
    form_class = SignupForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        """
        Returns form invalid if user with provided email already exists,
        returns form valid otherwise.
        """
        email = form.cleaned_data['email']
        user = User.objects.filter(email=email).first()

        if user:
            form.add_error('email', 'Пользователь с таким email уже существует.')
            return self.form_invalid(form)

        return super().form_valid(form)


class UserProfileView(GetQuerysetAndContextObjectNameMixin, generic.DetailView):
    """A view for displaying details of user."""

    template_name = 'users/profile.html'

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        user = get_object_or_404(User, id=self.kwargs['pk'])
        context['own_profile'] = self.request.user == user
        return context


class UserUpdateView(VerifyUserMixin, GetQuerysetAndContextObjectNameMixin, generic.UpdateView):
    """A view for for updating details of user."""

    form_class = UserUpdateForm
    template_name = 'users/user_update.html'

    def get_success_url(self) -> str:
        """
        Get the URL to redirect to after a successful form submission.
        Returns:
            str: The success URL.
        """
        pk = self.kwargs['pk']
        return reverse_lazy('users:user_profile', kwargs={'pk': pk})


class UserDeleteView(VerifyUserMixin, GetQuerysetAndContextObjectNameMixin, generic.DeleteView):
    """A view for deleting a user"""

    template_name = 'users/user_delete.html'
    success_url = reverse_lazy('users:login')

users/templates/users/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load bootstrap4 %}

{% block title %} Вход в аккаунт {% endblock %}

{% block content %}
    <section class="content-header">
        <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
            <h1>Вход в аккаунт</h1>
            </div>
            <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item active"><a href="{% url 'main_page' %}">Главная</a></li>
                <li class="breadcrumb-item">Вход в аккаунт</li>
            </ol>
            </div>
        </div>
    </section>
    
    <section class="content">
        <div class="container">
            <div class="d-flex justify-content-center">
                <div class="col-lg-6">
                    <form method="post" class="text-center">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button type="submit" class="btn btn-primary btn-lg w-50">Войти</button>
                        <hr />
                        <p>Забыли пароль? <a href="{% url 'users:password_reset' %}">Восстановить</a></p>
                        <p>Нет аккаунта? <a href="{% url 'users:signup' %}">Создать</a></p>
                        <p>Логин и пароль для демо доступа: <b>demo demo1234</b></p>
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

users/templates/users/password_change.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load bootstrap4 %}

{% block title %} Изменение пароля {% endblock %}

{% block content %}
    <section class="content-header">
        <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Изменение пароля</h1>
            </div>
            <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item active"><a href="{% url 'main_page' %}">Главная</a></li>
                <li class="breadcrumb-item">Аккаунт</li>
                <li class="breadcrumb-item">Изменение пароля</li>
            </ol>
            </div>
        </div>
    </section>
    
    <section class="content">
        <div class="container">
            <div class="d-flex justify-content-center">
                <div class="col-lg-6">
                    <form method="post" class="text-center">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button type="submit" class="btn btn-primary btn-lg w-50">Изменить</button>
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

users/templates/users/password_reset.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load bootstrap4 %}

{% block title %} Восстановление пароля {% endblock %}

{% block content %}
    <section class="content-header">
        <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Восстановление пароля</h1>
            </div>
            <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item active"><a href="{% url 'main_page' %}">Главная</a></li>
                <li class="breadcrumb-item">Восстановление пароля</li>
            </ol>
            </div>
        </div>
    </section>
    
    <section class="content">
        <div class="container">
            <div class="d-flex justify-content-center">
                <div class="col-lg-6">
                    {% if user.is_authenticated %}
                        <p>Вы уже вошли в аккаунт/p>
                    {% else %}
                        <form method="post" class="text-center">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <button type="submit" class="btn btn-primary btn-lg w-50">Восстановить</button>
                            <hr />
                            <p>Вспомнили пароль? <a href="{% url 'users:login' %}">Войти</a></p>
                        </form>
                    {% endif %}
                </div>
            </div>
        </div>
    </section>
{% endblock %}

users/templates/users/password_reset_complete.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title %} Пароль успешно изменен {% endblock %}

{% block content %}
    <section class="content-header">
        <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Ваш пароль успешно изменен!</h1>
            </div>
            <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item active"><a href="{% url 'main_page' %}">Главная</a></li>
                <li class="breadcrumb-item">Пароль успешно изменен</li>
            </ol>
            </div>
        </div>
    </section>
    
    <section class="content">
            <div class="d-flex justify-content-center">
                    <h4>
                        Нажмите <a href="{% url 'users:login' %}">здесь</a> чтобы авторизоваться с новым паролем.
                    </h4>
            </div>
    </section>
{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load bootstrap4 %}

{% block title %} Восстановление пароля {% endblock %}

{% block content %}
    <section class="content-header">
        <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Введите новый пароль</h1>
            </div>
            <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item active"><a href="{% url 'main_page' %}">Главная</a></li>
                <li class="breadcrumb-item">Восстановление пароля</li>
            </ol>
            </div>
        </div>
    </section>
    
    <section class="content">
        <div class="container">
            <div class="d-flex justify-content-center">
                <div class="col-lg-6">
                    {% if user.is_authenticated %}
                        <p>Вы уже вошли в аккаунт/p>
                    {% else %}
                        <form method="post" class="text-center">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <button type="submit" class="btn btn-primary btn-lg w-50">Изменить</button>
                        </form>
                    {% endif %}
                </div>
            </div>
        </div>
    </section>
{% endblock %}

users/templates/users/password_reset_done.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title %} Восстановление пароля {% endblock %}

{% block content %}
    <section class="content-header">
        <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Восстановление пароля</h1>
            </div>
            <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item active"><a href="{% url 'main_page' %}">Главная</a></li>
                <li class="breadcrumb-item">Восстановление пароля</li>
            </ol>
            </div>
        </div>
    </section>
    
    <section class="content">
            <div class="d-flex justify-content-center">
                    <h4>
                        Мы отправили вам на почту письмо с инструкцией по восстановлению пароля.
                        Обычно письмо приходит в течение 5 минут.
                    </h4>
            </div>
    </section>
{% endblock %}

users/templates/users/password_reset_email.html
<p>Hi</p>

<p>You're receiving this email because you requested a password reset for your user account at {{domain}}/</p>

<p>Please click the following link to reset your password:</p>

{{ protocol }}://{{ domain }}{% url "users:password_reset_confirm" uidb64=uid token=token %}

<p>Best regards!</p>
<p>PyCRM Team</p>

users/templates/users/profile.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title %}Профайл пользователя {{ user }}{% endblock %}

{% block content %}
    <section class="content-header">
        <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Информация о пользователе {{ user.username }}</h1>
            </div>
            <div class="col-sm-6 d-none d-sm-block">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item active"><a href="{% url 'main_page' %}">Главная</a></li>
                    <li class="breadcrumb-item active">{{ user }}</li>
                </ol>
            </div>
        </div>
        </div>
    </section>

    <section class="content-body">
        <div>
            <h4>Имя: {{ user.first_name }} {{ user.last_name }}
                <br />
                <br />
               Почта: {{ user.email }}
            </h4>
        </div>
        <br />
        <hr />
        <br />
        <div>
        {% if own_profile %}
            <a class="btn btn-primary btn-primary btn-lg" href="{% url 'users:password_change' %}">
                <i class="fas fa-sync"></i>
                Изменить пароль
            </a>
            <a class="btn btn-warning btn-lg" href="{% url 'users:user_update' user.pk %}">
                <i class="fas fa-pen"></i>
                Редактировать
            </a>

            <a class="btn btn-primary btn-danger btn-lg" href="{% url 'users:user_delete' user.pk %}">
                <i class="fas fa-times"></i>
                Удалить аккаунт
            </a>
        {% endif %}
        </div>
    </section>
{% endblock %}

users/templates/users/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load bootstrap4 %}

{% block title %} Регистрация нового аккаунта {% endblock %}

{% block content %}
    <section class="content-header">
        <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Регистрация нового аккаунта</h1>
            </div>
            <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item active"><a href="{% url 'main_page' %}">Главная</a></li>
                <li class="breadcrumb-item">Регистрация нового аккаунта</li>
            </ol>
            </div>
        </div>
    </section>
    
    <section class="content">
        <div class="container">
            <div class="d-flex justify-content-center">
                <div class="col-lg-6">
                    {% if user.is_authenticated %}
                        <p>Вы уже зарегистрированы</p>
                    {% else %}
                        <form method="post" class="text-center">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <button type="submit" class="btn btn-primary btn-lg w-50">Зарегистрировать</button>
                            <hr />
                            <p>Уже зарегистрированы? <a href="{% url 'users:login' %}">Войти</a></p>
                        </form>
                    {% endif %}
                </div>
            </div>
        </div>
    </section>
{% endblock %}

users/templates/users/user_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load bootstrap4 %}

{% block title %} Удаление аккаунта {{ user }} {% endblock %}

{% block content %}
    <section class="content-header">
        <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
            <h1>Вы уверены, что хотите удалить свой аккаунт?</h1>
            </div>
            <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item active"><a href="{% url 'main_page' %}">Главная</a></li>
                <li class="breadcrumb-item">
                    <a href="{% url 'users:user_profile' user.pk %}">{{ user }}</a>
                </li>
                <li class="breadcrumb-item">Удаление аккаунта</li>
            </ol>
            </div>
        </div>
    </section>
    
    <section class="content">
        <div class="col-lg-6">
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-primary btn-lg w-50">Удалить</button>
            </form>
        </div>
    </section>
{% endblock %}

users/templates/users/user_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load bootstrap4 %}

{% block title %} Обновление информации о пользователе {{ user }} {% endblock %}

{% block content %}
    <section class="content-header">
        <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
            <h1>Обновление информации о пользователе {{ user }}</h1>
            </div>
            <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item active"><a href="{% url 'main_page' %}">Главная</a></li>
                <li class="breadcrumb-item">
                    <a href="{% url 'users:user_profile' user.pk %}">{{ user }}</a>
                </li>
                <li class="breadcrumb-item">Обновление информации</li>
            </ol>
            </div>
        </div>
    </section>
    
    <section class="content">
        <div class="container">
            <div class="d-flex justify-content-center">
                <div class="col-lg-6">
                    <form method="post" class="text-center">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button type="submit" class="btn btn-primary btn-lg w-50">Обновить</button>
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock %}